In [2]:
import numpy as np
import gymnasium as gym
import random
import time

In [3]:
env = gym.make('FrozenLake-v1', render_mode='human', is_slippery=False)

In [4]:
numActions = env.action_space.n
numStates = env.observation_space.n

In [5]:
print(numActions,numStates)

4 16


In [6]:
#next build the q table
Q = np.zeros((numStates, numActions))

In [7]:
print(Q)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
#parameters
nE = 10000
mpE = 80
alpha = 0.1
gamma = 0.9
epsilon = 1
edr = 0.001

In [ ]:
#loop for the episodes
for e in range(nE):
    state = env.reset()
    done = False
    for step in range(mpE):
        if np.random.rand > epsilon:
            action = np.argmax(Q[state,:])
        else:
            action = env.action_space.sample()

DependencyNotInstalled: pygame is not installed, run `pip install "gymnasium[toy-text]"`